var categories = {
  "minecraft_pmobs": {
    "name": "Passive Mobs",
    "source": "http://https://www.digminecraft.com/mobs/index.php/",
    "values": [
      "Sheep",
      "Cow",
      "Fox",
      "Bat",
      "Chicken",
      "Cod",
      "Ocelot",
      "Pig",
      "Rabbit",
      "Salmon",
      "Mooshroom",
      "Squid",
      "Tropical fish",
      "Turtle",
      "Villager",
      "Pufferfish",
      "Donkey",
      "Horse",
      "Cat",
      "Parrot",
      "Mule",
      "Dolphin",
      "Polar bear",
      "Trader llama",
      "Llama",
      "Panda",
      "Wolf",
      "Bee",
      "Iron golem"
    ]
  },
  "minecraft_effects": {
    "name": "Potion Effects",
    "source": "https://",
    "values": [
      "Speed",
      "Slowness",
      "Haste",
      "Mining Fatigue",
      "Strength",
      "Instant Health",
      "Instant Damage",
      "Jump Boost",
      "Nausea",
      "Regeneration",
      "Resistance",
      "Fire Resistance",
      "Water Breathing",
      "Invisibility",
      "Blindness",
      "Night Vision",
      "Hunger",
      "Weakness",
      "Poison",
      "Wither"
    ]
  },
  "minecraft_hmobs": {
    "name": "Minecraft Mobs",
    "source": "http://https://www.digminecraft.com/mobs/index.php/",
    "values": [
      "Blaze",
      "Creeper",
      "Drowned",
      "Guardian",
      "Ender Dragon",
      "Endermite",
      "Enderman",
      "Evoker",
      "Ghast",
      "Hoglin",
      "Husk",
      "Illusioner",
      "Phantom",
      "Magma Cube",
      "Pigman",
      "Piglin",
      "Pillager",
      "Ravager",
      "Silverfish",
      "Shulker",
      "Skeleton",
      "Slime",
      "Stray",
      "Vex",
      "Vindicator",
      "Witch",
      "Wither",
      "Zoglin",
      "Zombie"
    ]
  }
};
